# -*- coding: utf-8 -*-
"""ac3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/JoaoAlves92/b303fc17470c2643c261918af5934590/ac3.ipynb

## O que são medidas de dispersão?

R: As medidas de dispersão são valores que nos dizem a variação dos dados em relação a média.

## Qual a diferença entre Desvio Médio Absoluto para Desvio Padrão?

R: O desvio médio absoluto é o valor real do desvio de uma variável em relação a sua média, já o desvio padrão é a raiz quadrada da variância. O desvio padrão é o mais comumente usado em análises.

## O que é amplitude interquartil?

R: A amplitude interquartil serve para avaliar o grau de espalhamento dos dados em relação a uma medida central, neste caso, com os dados ordenados em ordem crescente.

## Quais são as simetrias de um histograma e quais são as diferenças de cada uma?

R: Temos o simétrico ele centraliza os dados e contem o maximo de informações dentro dos que estão no centro e os mais perto do desvio padrão

distorcido para a direita, indicas valores com alto valor e baixa frequencia, donde visto o grafico da direita  para esquerda o valor vai do mai alto até o mais baixo quanto a frequencia so aumenta.

distorcido para a esquerdan donde é a mesma coisa do anterior porem a frequência dos dados é mais concentrada nos altos valores.

Bimodal, chamamos ela assim devido a haver 2 picos onde da pra perceber que a frequencia foi mais alta em 2 momentos

Multimodal, é pelo mesmo motivo da anterior porem há mais de 2 picos no grafico

Platô, o grafico fica neste formado devido a varios dados com o mesmo valor no grafico ficando todos juntos quase na mesma altura.

## Quais são as propriedades de um boxplot?

R: Com o Boxplot podemos analisar os dados de mediana, amplitude, outliers,o mínimo, o primeiro quartil (Q1), o terceiro quartil (Q3) e o máximo de maneira mais sucinta.

Em um boxplot sua altura do retângulo é definida pelos quartis Q1 e Q3. Uma linha que pega do retângulo no valor da mediana. As semirretas ligam respectivamente os quartis Q1 e Q3 ao valor mínimo e ao máximo do conjunto de dados.
"""

import pandas as pd
import matplotlib.pyplot as plt

# importando a base de dados
df = pd.read_csv('Diabetes.csv')

print('desvio médio absoluto\n')
print(df.mad(), '\n')

print('desvio padrão\n')
print(df.describe().loc['std'])

print('Intervalo Interquartil de Gravidezes:')
print(df.describe()['Pregnancies']['75%'] - df.describe()['Pregnancies']['25%'], '\n')

print('Intervalo Interquartil de Idades:')
print(df.describe()['Age']['75%'] - df.describe()['Age']['25%'])

x1 = 0
y1 = df['Outcome'].value_counts()[0]

x2 = 1
y2 = df['Outcome'].value_counts()[1]

plt.bar(x1, y1, color='green', label='Sem diabetes')
plt.bar(x2, y2, color='blue', label='Com diabetes')
plt.title('Gráfico de pessoas com ou sem diabetes')
plt.ylabel('Quantidade de pessoas')
plt.legend()
plt.show()

linha = df.sort_values('BMI')['BMI'].values #df.sample(100).sort_values('BMI')['BMI'].values
plt.plot(linha)
plt.ylabel('BMI')
plt.title('Gráfico de linhas BMI')
plt.show()

plt.hist(df['Age'])
plt.xlabel('Idades')
plt.ylabel('Quantidade de pessoas')
plt.title('Histograma de idades')
plt.show()

plt.boxplot(df['Pregnancies'])
plt.ylabel('Numero de gravidezes')
plt.title('Boxplot de gravidezes')
plt.show()

"""# Análise do Boxplot

---

Podemos ver logo de cara no boxplot 3 outliers do número de gravidezes. Também é possível identificar que 50% dos dados estão compreendidos entre 2 e 6 gravidezes, mostrando que acima de 75% dos valores são números de gravidezes bem altos.

#Referências 

---


*   https://acervolima.com/python-pandas-series-mad-para-calcular-o-desvio-medio-absoluto-de-uma-serie/

*   https://matplotlib.org/

*   https://operdata.com.br/blog/como-interpretar-um-boxplot/

*   https://www.alura.com.br/artigos/o-que-e-um-histograma#:~:text=Tipos%20de%20histograma-,Sim%C3%A9trico,o%20maior%20n%C3%BAmero%20de%20dados
"""